service: jmlparty-api
frameworkVersion: 4.4.7
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  memorySize: 512
  timeout: 29
  versionFunctions: false
  endpointType: REGIONAL
  deploymentBucket:
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameter*
      Resource:
        - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/${self:service}/google-auth/*

plugins:
  - serverless-domain-manager

custom:
  apiPath:
    production: api.jml.party
    other: api-${self:provider.stage}.jml.party
  createCustomDomain:
    production: true
    other: false
  customDomain:
    domainName: ${self:custom.apiPath.${self:provider.stage}, self:custom.apiPath.other}
    certificateName: '*.jml.party'
    stage: ${self:provider.stage}
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
    enabled: ${self:custom.createCustomDomain.${self:provider.stage}, self:custom.createCustomDomain.other}

functions:
  visitors:
    handler: src/functions/visitors.handler
    events:
      - http:
          path: visitors
          method: get
          cors:
            origin: '*'
            headers: '*'
            cacheControl: 'max-age=300, s-maxage=300, proxy-revalidate'
      - http:
          path: visitors/{party}
          method: get
          cors:
            origin: '*'
            headers: '*'
            cacheControl: 'max-age=300, s-maxage=300, proxy-revalidate'
          request:
            parameters:
              paths:
                party: true
    environment:
      GOOGLE_AUTH_TYPE: /${self:service}/google-auth/type
      GOOGLE_AUTH_PROJECT_ID: /${self:service}/google-auth/project_id
      GOOGLE_AUTH_PRIVATE_KEY_ID: /${self:service}/google-auth/private_key_id
      GOOGLE_AUTH_PRIVATE_KEY: /${self:service}/google-auth/private_key
      GOOGLE_AUTH_CLIENT_EMAIL: /${self:service}/google-auth/client_email
      GOOGLE_AUTH_CLIENT_ID: /${self:service}/google-auth/client_id
